{% set data = load_setup_py_data() %}

package:
  name: shenfun
  version: {{ data.get('version') }}

source:
  git_url: ../../
  #url: https://pypi.io/packages/source/s/shenfun/shenfun-{{ version }}.tar.gz

build:
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - numpy
    - setuptools
    - cython
    - pip
    - fftw

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pyyaml
    - scipy
    - fftw
    - mpi4py
    - mpi4py-fft >=2.0.3
    - sympy
    - pip
    - {{ mpi }}
    - h5py * mpi_{{ mpi }}_*
    - netcdf4 * mpi_{{ mpi }}_*

test:
  source_files:
    - tests
    - demo

  imports:
    - shenfun

  requires:
    - pip
    - pytest
