name: release

permissions:
  contents: read

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:

  distribution:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3

    - name: Upgrade pip
      run:  python -m pip install -U pip

    - name: Install build and twine
      run:  python -m pip install -U build twine

    - name: Build distribution
      run:  python -m build --sdist

    - name: Check source distribution
      run:  python -m twine check dist/*.tar.gz

    - name: Upload distribution assets
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: |
          dist/*.tar.gz


  pypi-publish:

    if: ${{ github.event_name == 'release' }}
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: distribution
    environment:
      name: pypi
      url: https://pypi.org/p/shenfun
    permissions:
      id-token: write

    steps:

    - name: Download distribution assets
      uses: actions/download-artifact@v4
      with:
        name: release
        path: dist

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
